### ISSUE TITLE
Errors in chart rendering

### ISSUE THREAD

**Issue by RBerliner** [rob42/freeboard-server#23]
I have run into a new problem with the chart display of the set of overlapping charts from NOAA 11552.

Below see the chart display of the extension of the Trent River.
 

![screenshot from 2016-06-24 12 31 58](https://cloud.githubusercontent.com/assets/3680585/16345143/5b3a9c2a-3a0e-11e6-927a-449d7b9a0557.png)

Note that there are 2 charts labeled Continuation of the Trent River (11552_2) drawn on top of each other and the topmost one is in the wrong place.

At a different zoom, I get what is expected:

![screenshot from 2016-06-24 12 32 56](https://cloud.githubusercontent.com/assets/3680585/16345154/6af25ba8-3a0e-11e6-8402-cdbafef88d66.png)

I dragged the openlayers.html file from 11552_2 into Chrome and I get:

![screenshot from 2016-06-24 12 36 11](https://cloud.githubusercontent.com/assets/3680585/16345164/798dbce8-3a0e-11e6-8571-9d6bbab5dc7c.png)

which seems just fine. 

Also, I get a passel of errors in the browser console about files that cannot be found.
[ConsoleLog.txt](https://github.com/rob42/freeboard-server/files/332168/ConsoleLog.txt)

I spot-checked the list of files and they are really not there so somebody is mis-calculating the signature of the tiles that are required.

An insight woulld be welcome..

**Comment by RBerliner** [comment]
The error is in maptools. When I try different zooms after dragging openlayers.html into Chrome, I also get bad rendering,
![screenshot from 2016-06-24 15 44 21](https://cloud.githubusercontent.com/assets/3680585/16348898/47391d54-3a23-11e6-9e8c-0328be0a53e7.png)

**Comment by rob42** [comment]
The 404 errors are not unusual, the leaflet map code is just trying to find tiles, the 404 is normal when they cant be found
GET http://localhost:8080/mapcache/11537_1/13/2341/4949.png 404 (Not Found)
Its related to the freeboard.txt file in the chart dir which holds meta data on the chart pyramid, but that this kind of error still happens when a layer has only partial coverage of the screen area. The map widget attempts to fill in the rest of the screen with tiles that dont exist and will fail.

**Comment by rob42** [comment]
Doh, commented and  closed it! Reopening..

May be worth checking your mapcache mapcache/11537_1 dir doesnt have any left-overs from previous chart processing. eg they are all the same date/time. You may have some garbage from your previous debugging on maptools.
Try right-click on the tile and see what url its found at, may give a hint. Also in the console in chrome, under 'network' will show what tiles were loaded when and in what order. May help..

**Comment by rob42** [comment]
Just a thought - its not related to trimming the chart border is it? The main charts have borders, the insets dont?. Could the border adjustment be applied incorrectly?.

**Comment by RBerliner** [comment]
Hi  Rob:

I had the same thought. No, the charts with borders behave the same way.

I will have more to say on this tomorrow.

Ron

On Fri, Jun 24, 2016 at 7:16 PM, rob42 <notifications@github.com> wrote:

> Just a thought - its not related to trimming the chart border is it? The
> main charts have borders, the insets dont?. Could the border adjustment be
> applied incorrectly?.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rob42/freeboard-server/issues/23#issuecomment-228486401>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADgpSWkRwNnGQIlr1CPIR5zK79LRELAAks5qPGVTgaJpZM4I99ho>
> .
>



-- 

R. Berliner
Instrumentation Associates
101 Echowood Ln
Cary, NC 27518

e-mail: rberliner@InstrumentationAssociates.com

www.InstrumentationAssociates.com <http://www.InstrumntationAssociates.com>

Tel     734-646-5318

**Comment by rob42** [comment]
Since fixed in https://github.com/rob42/freeboard-installer/pull/4
https://github.com/SignalK/maptools/pull/7
https://github.com/SignalK/maptools/commit/a50d7aa93f6d591132fa8e8b1d4d009697e27428
https://github.com/SignalK/maptools/commit/faca2d96d1e8389853edfd67172ed2062dbf9197
https://github.com/SignalK/maptools/commit/83faf21ab7c4db080588c6bd57e6f92690bac04a

Includes other changes to provide more zoom levels and misc.
